events {
    worker_connections 1000;
}

http {
    upstream web_backend {
        least_conn;
        server web:8000;
    }

    server {
        listen 80;
        server_name localhost;

        location /health {
            proxy_pass http://web_backend/health;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /predict {
            proxy_pass http://web_backend/predict;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            client_max_body_size 10M;
        }

        location /predict_array {
            proxy_pass http://web_backend/predict_array;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            client_max_body_size 10M;
        }

        location /docs {
            proxy_pass http://web_backend/docs;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /openapi.json {
            proxy_pass http://web_backend/openapi.json;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
